### ISSUE TITLE
Regression in description generation

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#113]
See https://github.com/Azure/autorest.modelerfour/commit/cb06cf730dc0534a1ac10b2fb262843d13c4c9f3#diff-a8e947cdf7681525c5ee9a162ee0ee85R1653

**Comment by fearthecowboy** [comment]
Bug in text-analytics swagger :

It's actually pointing out a rather terrible flaw in the original swagger file.

``` json
    "documentScores": {
          "description": "Document level sentiment confidence scores between 0 and 1 for each sentiment class.",
          "$ref": "#/definitions/SentimentConfidenceScorePerLabel"
        },
```

The `$ref` in this case is pointing to a _schema_ and not to a referenced _parameter_ 

They should be using : 
``` json
"documentScores": {
          "description": "Document level sentiment confidence scores between 0 and 1 for each sentiment class.",
           "schema": {
              "$ref": "#/definitions/SentimentConfidenceScorePerLabel"
           },
        },
```

and because the ambiguity in how things are declared, it was actually treating the target as a parameter. 

Which means that we have to add in some validation of `$ref` paths (ie, what it's for has to be $ref'd to the right location)

O_O

// cc: https://github.com/Azure/autorest/issues/3359

**Comment by fearthecowboy** [comment]
I'm closing this because it's an input file issue.
