### ISSUE TITLE
Method parameters are sorted in modelerfour, and which is not consistent with swagger

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.modelerfour#126]
In modeler four, it order the parameters of one method, seems path parameters are ahead of body parameter.
But modeler v1 does not order the method paramters, and keep the parameter order as the same the way defined in API swagger file.

As a result, the parameter order is not consistent with current GO-SDK which use moderler v1.

Is ordering method parameter by design in modelerfour?
If so, would you please tell me the order rules so that GO-SDK can apply the same order rule to avoid in-consistence?

Thanks,

**Comment by RodgeFu** [comment]
@fearthecowboy , is it possible to have a configure to honor the original parameter order defined in swagger so that our Terraform CodeGen can know how to call the current GoSDK? Or as a workaround, is it possible for us to know the line# of the parameter defined in swagger file so that we can figure out the order in through that? 

Please help to mark IMPORTANT  tag. This is a blocking issue for Terraform CodeGen which will depend on current GO SDK now. The Track 2 Go SDK's timeline is too late so we can't wait for that. thanks.

**Comment by fearthecowboy** [comment]
Wait-- you're trying to code against the Go SDK by using the modelerfour as the means to predict generated APIs and models?!

That simply is not going to be reliable. The whole point of the autorest V3 pipeline was to permit the ability for one v3 generator to know what another v3 generator was going to do based on the code model. What you're doing, is trying to predict what a v2 generator is doing based on what the v3 modeler is doing. 

We have **different** interpretations in V3 of how swagger is translated into code. Names, order, model construction, grouping ... *everything* is potentially different. 

I can't possibly make modelerfour do what you're asking, as we're trying to fix underlying problems.

**Comment by chunyu3** [comment]
Is is no about autorest V3.
Terraform calls Go-SDK to manage Azure resource.  We generate code for terraform to call Go-SDK. Since Go-SDK is consistent with swagger, we can generate code according to the swagger, that is we will generate code according to the model which generated by modelerfour. 
Current scenario is that Go-SDK generated according to the modeler v1 which is consistent with swagger (no paramter ordering), and modelerfour orders the method parameters, as a result the terraform code generated according to modelerfour model will not consistent with Go-SDK.

Would you please tell us what is the ordering rules and if there is any way to avoid parameter ordering?

**Comment by RodgeFu** [comment]
@fearthecowboy, thanks for the reply, we have to use the existing Go SDK in our CodeGen because it still needs more time for the Go SDK based on modelerfour to be ready. I can understand that the new modelerfour are processing the swagger in a different way and hard to force it to honor some specific order. Then is it possible for us to get the line# of the parameter defined in swagger in modelerfour so that we can use it as a hint to handle the ordering problem in our CodeGen? That should be good enough for us. Thanks.

As for the potential breaking change from the different parameter orders in SDK, I will start a mail thread to discuss about it involving more people. thanks.

**Comment by fearthecowboy** [comment]
// covered in email
