### ISSUE TITLE
Response of any not being included in list of schemas

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#198]
**Describe the issue**
When generating web 2016-09, I have a [response](https://github.com/Azure/azure-rest-api-specs/blob/58c68dea43b9924fedaf819bfead1bc922fe9143/specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/AppServicePlans.json#L803) that has a schema type of Any. However, this schema is not included in the list of schemas under "any". Since python generates from the list of schemas first, we would like for this to be included in the list of schemas.

** REQUIRED ** 
**ModelerFour** version: 4.9.234
**AutoRest-core** version: 3.0.6246
**CommandLine** : autorest ..\azure-rest-api-specs\specification\web\resource-manager\readme.md --use=. --multiapi --python-sdks-folder=..\azure-sdk-for-python\sdk --python
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/web/resource-manager/Microsoft.Web/stable/2016-09-01/AppServicePlans.json

**Comment by daviwil** [comment]
Discussed this with @iscai-msft and @lmazuel on Teams, we discovered that `AnySchema` is a singleton schema (only one instance will exist in the resulting CodeModel) which indicates that any object type should be expected there (roughtly translating to `object` or `any` in languages with that concept).

This schema type is intentionally left out of `codeModel.schemas` because it serves as a signifier and not a schema with details that must be used by a generator.  Language generator extensions will need to check for the `any` schema type and use a deserializer generic enough to catch any generally supported types in this case (primitives, collections, and simple key/value object types).
