### ISSUE TITLE
ModelerFour is missing some swagger definitions

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.modelerfour#220]
**Describe the issue**

When I am trying to onboard datafactory using autorest az. I found that some Trigger definition in swagger is misssing.
I am using this branch as input https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/readme.md

And there's a BlobTrigger in here https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L248

but in the modelerfour output,  I can't find the BlobTrigger definition

** REQUIRED ** 
**ModelerFour** version: 4.10.250
**AutoRest-core** version: 3.0.6253
**CommandLine** : autorest --modelerfour --use=@autorest/modelerfour@4.10.250 --output-artifact=code-model-v4-no-tags ../azure-rest-api-specs/specification/datafactory/resource-manager/readme.md --debug --output-folder=/tmp/aztest
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/readme.md

**Comment by qiaozha** [comment]
Not sure if this helps.
but the `Trigger` https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L9 is the polymorphic base class.
And `MutipliePipelineTrigger` https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L55 is the subclass of `Trigger`
And `BlobTrigger` https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L248  is the subclass of ``MutipliePipelineTrigger`

**Comment by RodgeFu** [comment]
@fearthecowboy , could you help to have a look? this is blocking our onboard of datafactory now. thanks.

**Comment by fearthecowboy** [comment]
`BlobTrigger` doesn't have an `x-ms-discriminator-value` so it doesn't know that it's a model that it should keep. 

Files that are not specified in `input-file` only pull in models that are referenced directly (ie, via `$ref` ), the parent of something pulled in via a `$ref`, a model referenced by a property in a type that was `$ref`'d  or a polymorphic child class of something pulled in via `$ref` (which requires `x-ms-discriminator-value`) .. all other models are dropped because they were not used or referenced.

You either have to give BlobTrigger an `x-ms-discriminator-value` (which it uses to infer that it's a possibly used type) or you have to add the `entityTypes/Trigger.json` file as an `input-file:` in the configuration, in which case all the models are pulled in without question.

**Comment by qiaozha** [comment]
@fearthecowboy Thank you. it works.
