### ISSUE TITLE
Body parameter required attribute value inconsistent across media types

### ISSUE THREAD

**Issue by chradek** [Azure/autorest.modelerfour#239]
When an operation supports json and binary media types but the request body parameter is not marked as required, modelerfour correctly marks the `json` body parameter as not required but marks the `binary` body parameter as required.

I would have expected the `required` value to be the same for both media types.

Is there a reason binary media types are marked required by modelerfour but not json?

Note: In modelerfour v4.10.268 the required fields were consistent, but I only tested the not required scenario.

**ModelerFour** version: 4.12.276
**AutoRest-core** version: 3.0.6246
**CommandLine** : autorest --typescript --add-credentials=false --output-folder=./test/integration/generated/mediaTypes --use=. --title=MediaTypesClient --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/media_types.json --package-name=media-types-service --package-version=1.0.0-preview1
OpenAPI/Swagger file: https://github.com/Azure/autorest.testserver/blob/master/swagger/media_types.json

**Comment by lmazuel** [comment]
There is a design discussion to have on `binary` and `required`, and taking your issue as hostage to host it :)

Right now, autorest consider any operation that has a binary as input, that the parameter is automatically forced as `required`. The concept is that in most situation (we actually never seen otherwise in practical terms), an operation that takes a binary as input requires it. So autorest force it as required, whatever the Swagger is saying.

So the question is: do we want the `required` behavior to be set only if it was written explicitly in the Swagger as required, and drop the "binary is auto-required".

This may have impact on currently used Swagger files, that could be fixed by defining an explicit "parameter" with "required:true"

**Comment by fearthecowboy** [comment]
and it means that in cases where the body parameter is declared for the json body, that (in spite of the rest of the parameter details being about serializing json), the 'required' value would be borrowed for the binary parameter

**Comment by daviwil** [comment]
The impact of this issue related to @chradek's report is that when you have an operation with 2 requests, one that is binary and the other that's JSON, the binary request's body parameter will be set with `required: true` yet the JSON request does not get `required: true` added automatically.  This causes some inconsistency when generating overloads between the two requests for the operation.

**Comment by fearthecowboy** [comment]
And just to clarify; the use of `content-type` is dependent on the presence of a body; so if I make the body not required, then by extension, I should make the synthetic content-type parameter not required, but constants can't be optional, so it's gonna have to end up creating a single-value enum for the content-type and another optional parameter

And then there is no way to enforce both or none.

**Comment by chradek** [comment]
But in this case the body for the `json` media type is not required. There is a content-type parameter that is a constant and is required, but the body is not. I'd be fine if the body parameter was required for the `json` media type as well, but maybe that's even more controversial.

**Comment by fearthecowboy** [comment]
Well, if it were up to me, body params would be always be required. I don't see the real-world scenario for having an optional body parameter. It's just silly, and will lead to to bad sdks.

**Comment by fearthecowboy** [comment]
We theoretically should be making the `content-type` parameter consistent to the body parameter. I just think there isn't an SDK in the world where you would want to have to specify the content-type and the body object both, or neither. It's just painful.

**Comment by fearthecowboy** [comment]
So, what's the outcome here?

1 - Just follow the swagger as best it can, if it doesn't say `required`,  it's not (and you'll get an optional `content-type` parameter when that gets generated too.

2 - Required be dammed! Make body parameters always required (and `content-type` too)

3 - CrazyMode! Binary body parameters and the content-type are always required, JSON/XML body parameters follow the swagger (and if it creates `content-type` , that 'd be optional there. 

Frankly, none of those options are great.

**Comment by lmazuel** [comment]
@chradek being the scenario we saw so far, binary implying required is fair.

That brings the question what to do if you have multiple requests when the same parameter is optional in one, and required in the other one (which is actually more your issue than the binary discussion was).

On the Python side, we have no overload, and we decided the final unique parameter will be optional, unless all of them are required. This should allow the flexibility we want, and the server will complain anyway, so you have some feedback likely at some point.

In the particular case of FormRecognizer, we should make it required anyway explicitly, and we should likely change the testserver test for that (since it's actually what I meant)

**Comment by chradek** [comment]
For JavaScript I updated our generator to support overloads that have different parameters defined. If the body is optional, it shows up in our final, 'options' bag, and if it is required it shows up as a positional argument. This is no longer a blocker for us updating to the latest modelerfour.
