### ISSUE TITLE
Running into FATAL bad indentation error while generating network 2018-01

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#270]
**Describe the issue**
When running network 2018-01, i get this error:
![image](https://user-images.githubusercontent.com/43154838/80146193-7b0cd200-857f-11ea-8741-2e0e39c5c8c4.png)

I've tried running it with 4.12.301 and "http://tinyurl.com/y962y5mg", and I tried running each both with and without --ignore-errors flag and they all fail here.

Appears to arise from within the examples in the network rest api specs repo

** REQUIRED ** 
**ModelerFour** version: 4.12.301 and "http://tinyurl.com/y962y5mg"
**AutoRest-core** version: 3.0.6265
**CommandLine** : autorest ../azure-rest-api-specs/specification/network/resource-manager/readme.md --python --use=. --python-sdks-folder=../azure-sdk-for-python/sdk --tag=package-2018-01 --track2 --python-mode=update (have tried with and without --ignore-errors too)
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2018-01-01

**Comment by pakrym** [comment]
Same for websites https://github.com/Azure/autorest.csharp/issues/674

**Comment by zikalino** [comment]
I encountered this issue as well. in my case it was because of this particular example:

https://github.com/Azure/azure-rest-api-specs/blob/cd01bd0b8c633cea7d1ac022cae176a0b9b7985c/specification/network/resource-manager/Microsoft.Network/stable/2018-01-01/examples/ApplicationGatewayAvailableSslOptionsPredefinedPoliciesGet.json#L9

It seems there's a nested array in there which is not correct (same example is different in previous and later version of that example, this example version seems edited manually)

Please note that i generates this kind of yaml:

responses:
            '200':
              body:
                value:
                - - name: AppGwSslPolicy20150501
                  id: /subscriptions/subid/resourceGroups//providers/Microsoft.Network/ApplicationGatewayAvailableSslOptions/default/ApplicationGatewaySslPredefinedPolicy/AppGwSslPolicy20150501
                  properties:
                    cipherSuites:

This yaml is perfectly valid, it seems like there's a problem with parser that doesn't support nested arrays ("- -").

**Comment by daviwil** [comment]
I'm pretty confident that PR https://github.com/Azure/perks/pull/105 fixes this issue, it's now been released in `@autorest/modelerfour` [4.13.351](https://github.com/Azure/autorest.modelerfour/releases/tag/v4.13.351).  Please try it out and let me know if it works for you!

**Comment by iscai-msft** [comment]
i can confirm for network, @pakrym I tried to generate web, but running into an error on the python side, can you confirm?

**Comment by pakrym** [comment]
After adding support for CredentialSchema I was able to generate web locally, figuring out why CI fails.

**Comment by pakrym** [comment]
Failing even without parallelism. I guess we can live with it for now but might be an issue long term.

**Comment by daviwil** [comment]
I think Web is fine with the latest release.  Is there any other spec that fails due to the YAML indentation error?

**Comment by daviwil** [comment]
I've fixed @pakrym's issue (and a couple others since) so I think it's safe to close this one now.  Thanks!
