### ISSUE TITLE
FATAL: Error: Not able to process media type multipart/form-data at this moment. (BodyFormData)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#28]
Crash of modelerfour

**Comment by weidongxu-microsoft** [comment]
Got this one as well, from web service.

`FATAL: Error: Not able to process media type application/zip at this moment.`

**Comment by jianghaolu** [comment]
Johan suggests changing this to P0

**Comment by lmazuel** [comment]
Blocker for FormRecognizer
https://github.com/Azure/azure-rest-api-specs/blob/2e7ca21a5ad6f749e5bd453580f1c31c1d99b4e6/specification/cognitiveservices/data-plane/FormRecognizer/preview/v1.0/FormRecognizer.json#L258

**Comment by fearthecowboy** [comment]
Form Recognizer was bad swagger, and this should all be good now.

**Comment by mayurid** [comment]
Looks like we have addressed for form recognizer for now. This is backlog item in case we have request for this feature

**Comment by MiYanni** [comment]
There are additional readmes (swaggers) being blocked by this. So, I'm making this a P1 since, at minimum, they would need investigation. These would need to be generated at some point (either via swagger change or M4 change).

Affected readmes:
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/cognitiveservices/data-plane/ComputerVision/readme.md
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/cognitiveservices/data-plane/ContentModerator/readme.md
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/cognitiveservices/data-plane/CustomVision/Prediction/readme.md
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/cognitiveservices/data-plane/CustomVision/Training/readme.md
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/containerregistry/data-plane/readme.md
- https://github.com/Azure/azure-rest-api-specs/blob/d9cf7c7ed3d674ebd482836e82b274014245ae67/specification/machinelearningservices/data-plane/readme.md

**Comment by MiYanni** [comment]
Confirm fixed (for .NET) via https://github.com/Azure/autorest.csharp/pull/886. Closing.
