### ISSUE TITLE
Autorest treats integer as int32 by default

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#288]
> Jeffrey Richter
    
> Interpretation of Swagger "integer"
> 
> It has come to my attention that autorest treats a swagger “integer” (example: https://github.com/kasobol-msft/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json#L9093) as a 32-bit signed integer. However, this is a mistake. A JSON payload integer gets turned into a JavaScript number which has a range of –(2^53-1) to +(2^53-1) as shown here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number. Therefore, many languages should be treating a swagger “integer” as a 64-bit signed integer; not a 32-bit signed integer.
> 
>  Autorest should be updated and client libraries should be reviewed to correct any integer size issues.

See https://teams.microsoft.com/l/message/19:987876ab02634aaeaded0fb0de9f338a@thread.skype/1585930599367?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1585930599367&teamName=Azure%20SDK&channelName=AutoRest%20-%20Engineering&createdTime=1585930599367

conversation for context

**Comment by pakrym** [comment]
We need to decide what to do here before we GA any fully-generated libraries.

**Comment by daviwil** [comment]
I just read back over the initial conversation that @pakrym linked in the issue description.  It sounds like there isn't anything actionable to do in AutoRest/Modelerfour at this moment, correct?

@johanste's proposal was mainly to add a linting rule (which @lmazuel filed a request for) and gradually get all service Swaggers to explicitly specify the format for each usage of `integer`.  I got the impression that we want to hold off on making `int64` the default for now since that might be an unexpected change for service teams (and SDK library users).

**Comment by pakrym** [comment]
Sounds good.
