### ISSUE TITLE
Header response not available in YAML for "header_responseProtectedKey"

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#34]
Example with Headers JSON operation "header_responseProtectedKey":
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/header.json#L114-L117

Headers are not in the YAML. There is indeed a node "headers", but it doesn't point to the one I need to see

**Comment by lmazuel** [comment]
Hum, it works for "responseInteger", so not sure why it doesn't for this one operation

**Comment by fearthecowboy** [comment]
Gah! I think the schema deduplicator is overly aggressive with strings, and merging things that look the same but with different descriptions. 

I'm fixing that in autorest-core right now.

**Comment by fearthecowboy** [comment]
Holy-freaaaaaakin'-moley.

I dunno how this got in this far, but this turned out to be a bug in the OAI2->OAI3 converter accidentally leaving the the `x-ms-enum` extension on the header/value instead of the header/value/schema.

My brain hurts so much from finding this. 

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/header/code-model-v4.yaml#L2520

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/header/code-model-v4.yaml#L59

**Comment by fearthecowboy** [comment]
It now stored headers with the name split out correctly 

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/header/code-model-v4.yaml#L880

**Comment by lmazuel** [comment]
Fixed
