### ISSUE TITLE
Too many objects

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#47]
With 4.0.41, we get an object components·schemas·petaptrue·additionalproperties related to nothing 
Swagger AdditionalProperties

**Comment by lmazuel** [comment]
That's more generic than addProp, for instance in BodyArray:
paths·array-dictionary-itemempty·get·responses·200·content·application-json·schema·items

**Comment by lmazuel** [comment]
BodyDictionannary too

**Comment by fearthecowboy** [comment]
Nice Catch.

This was caused by a transform macro extremely early in AutoRest V3 -- we implicitly re-write `additionalProperties: true ` into `additionalProperties: { type: object}    ` ... where we end up creating an anonymous object type that after treeshaking, ends up in the list of schemas.

I've taken the extra step to not emit **empty** unreferenced schemas that have no discriminator, properties, parents or children.

**Comment by fearthecowboy** [comment]
fixed by #50 -- please confirm. (modelerfour - 4.0.46)

**Comment by lmazuel** [comment]
Fixed
